capstone_database/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dms/', include('dms.urls')),
    path('', include('dms.urls')),
]

dms/urls.py
from django.urls import path
from . import views

app_name = 'dms'

urlpatterns = [
    path('', views.home, name="database-home"),
    path('faculty/', views.faculty, name="database-faculty"),
    path('juniors/', views.studentJunior, name="database-juniors"),
]

dms/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

'''
Professors
Students
Alumni (a way to get the students to move to alumni every year)
'''

class StudentJunior(models.Model):
	timestamp = models.CharField(max_length=200)
	email = models.EmailField()
	name = models.CharField(max_length=200)
	collegeMajor = models.CharField(max_length=50, blank=True)
	primaryConc = models.CharField(max_length=100, blank=True)
	secondMajor = models.CharField(max_length=50, blank=True)
	secondConc = models.CharField(max_length=50, blank=True)
	customConc = models.CharField(max_length=100, blank=True)
	minor = models.CharField(max_length=50, blank=True)
	minorConc = models.CharField(max_length=50, blank=True)
	knowledge2Offer = models.TextField(blank=True)
	knowledge2Request = models.TextField(blank=True)
	section = models.CharField(max_length=50, blank=True)
	location = models.CharField(max_length=100, blank=True)
	topProjectIdea = models.TextField(blank=True)
	degreeCommitment = models.CharField(max_length=100, blank=True)
	projectFeatures = models.TextField(blank=True)
	otherProjectIdeas = models.TextField(blank=True)
	externalDependencies = models.TextField(blank=True)
	hsrReview = models.TextField(blank=True)
	relevantSkills = models.TextField(blank=True)
	slug = models.SlugField(max_length=200, blank=True)
	created = models.DateField(auto_now_add=True, db_index=True)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		'''
		Upon saving a slug is created
		'''
		if not self.slug:
			self.slug = slugify(self.email)
		super().save(*args, **kwargs)

class Faculty(models.Model):
	email = models.EmailField()
	name = models.CharField(max_length=200)
	colleges = models.CharField(max_length=200)
	coursesMinerva = models.TextField(blank=True)
	coursesElsewhere = models.TextField(blank=True)
	overviewExpertise = models.TextField(blank=True)
	expertiseKeywords = models.TextField(blank=True)
	additionalInterest = models.TextField(blank=True)
	links = models.TextField(blank=True)
	coursesDomainExpertise = models.TextField(blank=True)
	slug = models.SlugField(max_length=200, blank=True)
	created = models.DateField(auto_now_add=True, db_index=True)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		'''
		Upon saving a slug is created
		'''
		if not self.slug:
			self.slug = slugify(self.email)
		super().save(*args, **kwargs)

dms/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Faculty, StudentJunior

# Create your views here.

def home(request):
	return render(request, 'dms/home.html')

def faculty(request):
	faculty=Faculty.objects.all()

	return render(request, 'dms/faculty.html', {'faculty': faculty})


def studentJunior(request):
	students=StudentJunior.objects.all()

	return render(request, 'dms/juniors.html', {'students': students})

dms/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}Capstone Database{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'dms:database-juniors' %}">Juniors</a></li>
            <li><a href="{% url 'dms:database-faculty' %}">Faculty</a></li>


        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

dms/templates/dms/faculty.html
{% extends "base.html" %}

{% block title %}Faculty{% endblock %}

{% block content %} 


	This is the faculty page 

	<table style="width:100%">
		<tr> 
			<th>Email Address</th>
			<th>Name</th>
			<th>College(s)</th>
			<th>Courses taught at Minerva</th>
			<th>Courses taught elsewhere</th>
			<th>Overview of expertise and experience</th>
			<th>Expertise and experience - keywords</th>
			<th>Additional areas of interest</th>
			<th>Link(s) to additional relevant information </th>
			<th>Courses at Minerva that are within your domain of expertise (*numbers only*)</th>
		</tr>

		{% for item in faculty %}
		    <tr> 
		    	<td>{{ item.email }}</td>
		    	<td>{{ item.name }}</td>
		    	<td>{{ item.colleges }}</td>
		    	<td>{{ item.coursesMinerva }}</td>
		    	<td>{{ item.coursesElsewhere }}</td>
		    	<td>{{ item.overviewExpertise }}</td>
		    	<td>{{ item.expertiseKeywords }}</td>
		    	<td>{{ item.additionalInterest }}</td>
		    	<td>{{ item.links }}</td>
		    	<td>{{ item.coursesDomainExpertise }}</td>
		    </tr>
	    {% endfor %}
	</table>

{% endblock %}

dms/templates/dms/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}<h1>Welcome to the homepage</h1>{% endblock %}

dms/templates/dms/juniors.html
{% extends "base.html" %}

{% block title %}Juniors{% endblock %}

{% block content %} 


	This is the page for the juniors 

	<table style="width:100%">
		<tr> 
			<th>Timestamp</th>
			<th>Email Address</th>
			<th>Name</th>
			<th>College of your primary major</th>
			<th>"Primary" concentration</th>
			<th>Second Major</th>
			<th>Second concentration</th>
			<th>Custom / special concentration(s)</th>
			<th>Minor</th>
			<th>Minor concentration</th>
			<th>Knowledge / skill-sharing to offer</th>
			<th>Knowledge / skill-sharing request</th>
			<th>Section</th>
			<th>Where are you located this semester?</th>
			<th>Current top independent project idea</th>
			<th>Degree of commitment to this project</th>
			<th>Project features</th>
			<th>Other project idea(s)</th>
			<th>External dependencies</th>
			<th>HSR Committee review status</th>
			<th>Relevant skills & content knowledge</th>
		</tr>

		{% for item in students %}
		    <tr> 
		    	<td>{{ item.timestamp }} </td>
		    	<td>{{ item.email }} </td>
		    	<td>{{ item.name }} </td>
		    	<td>{{ item.collegeMajor }} </td>
		    	<td>{{ item.primaryConc }} </td>
		    	<td>{{ item.secondMajor }} </td>
		    	<td>{{ item.secondConc }} </td>
		    	<td>{{ item.customConc }} </td>
		    	<td>{{ item.minor }} </td>
		    	<td>{{ item.minorConc }} </td>
		    	<td>{{ item.knowledge2Offer }} </td>
		    	<td>{{ item.knowledge2Request }} </td>
		    	<td>{{ item.section }} </td>
		    	<td>{{ item.location }} </td>
		    	<td>{{ item.topProjectIdea }} </td>
		    	<td>{{ item.degreeCommitment }} </td>
		    	<td>{{ item.projectFeatures }} </td>
		    	<td>{{ item.otherProjectIdeas }} </td>
		    	<td>{{ item.externalDependencies }} </td>
		    	<td>{{ item.hsrReview }} </td>
		    	<td>{{ item.relevantSkills }} </td>
		    </tr>
	    {% endfor %}
	</table>

{% endblock %}